spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_test
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

app:
  name: My Externalized App
  message: My repo is dev please change it sdjd dhfhdf hdshf!
