spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_test
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

app:
  name: My Externalized App
  message: Hello This is my Dev Server hello to you 11111111111111!
